name: graphreasoning
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - cmake
  - torchvision=0.17.1
  - torchaudio=2.2.1
  - faiss-gpu=1.8.0
  - pip
  - git
  - pip:
    - python-dotenv==1.0.1
    - tqdm==4.66.5
    - matplotlib==3.9.0
    - numpy==1.26.4
    - scikit-learn==1.5.1
    - mlflow==2.15.1
    - azureml-mlflow==1.57.0
    - git+https://github.com/lamm-mit/GraphReasoning
    - langchain-community==0.3.17
    - llama-index-embeddings-huggingface==0.5.1
    - openai==1.63.0
    - ratelimit==2.2.1

